version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "16:00"
  open-pull-requests-limit: 10
  target-branch: development
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "weekly"
    day: saturday
    time: "10:00"
  target-branch: development
  open-pull-requests-limit: 10