name: Remove untagged images from registry

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

env:
  PACKAGE_NAME: webchanges

jobs:
  Delete_untagged_images:
    runs-on: ubuntu-latest
    steps:
      - name: Delete all images from repository without tags
        uses: Chizkiyahu/delete-untagged-ghcr-action@v6.1.0
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository_owner: ${{ github.repository_owner }}
          repository: ${{ github.repository }}
          package_name: ${{ env.PACKAGE_NAME }}
          untagged_only: true
          owner_type: user
          except_untagged_multiplatform: true
